<?php //if (isset($embed_url)):

global $post;

if($post->post_type == 'team' ) : ?>

<!-- Team profile Video -->

<?php $video = get_field('video'); ?>
 <div class="embed-responsive embed-responsive-1by1 video-wrap">

	 <video class="team-video" width="640" height="640" preload="auto" muted >
		<source src="<?php echo $video ?>" type="video/mp4">

			Your browser does not support the video tag.
		</video>
 </div>

 <?php else:

	 if($post->post_type == 'portfolio') :
		$embed = get_field('single_video');
		$embed_class = $embed['video_class'];
		$embed_url = $embed['video_url'];
		$embed_caption = $embed['embed_caption'];
		$aspectRatio = $embed['video_aspect_ratio'];

	else : //video generated by shortcode

		$embed_url = $video_url;
		$embed_caption = null;

	endif;
?>
<!-- Portfolio Videos and Interactives AND via the shortcode "embed_this" -->

<div class="embed-responsive embed-responsive-<?php echo $aspectRatio?> <?php echo ($embed_class != null ? $embed_class : '')?>">
  <iframe class="embed-responsive-item" src="<?php echo $embed_url?>"></iframe>

</div>
 <?php if(isset($embed_caption)) : ?>
 <span class="embed-caption"><?php echo $embed_caption?></span>

<?php endif;endif; ?>